FROM python:3.12-slim

RUN pip install --upgrade pip

COPY . .

RUN pip install -r requirements.txt

RUN apt-get update && \
    apt-get install -y dos2unix && \
    dos2unix scripts/telegrambot-init.sh && \
    chmod +x scripts/telegrambot-init.sh

ENTRYPOINT [ "scripts/telegrambot-init.sh" ]